# This is a basic workflow to help you get started with Actions

name: 🚀 Deploy website on push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0-beta
      with:
        server: ftp.gb.stackcp.com
        username: deploy@haresfootfarm.com
        password: ${{ secrets.ftp_password }}